import"./assets/styles-JE8YjOlG.js";import{a as n,i as r}from"./assets/vendor-CJ_tX8LA.js";const f="https://dummyjson.com",l={PRODUCTS:"/products",PRODUCT_BY_ID:"/products/",SEARCH:"/products/search",CATEGORY:"/products/category-list",PRODUCTS_BY_CATEGORY:"/products/category/"},a=12;n.defaults.baseURL=f;async function b(){const{data:e}=await n.get(`${l.CATEGORY}`);return e}async function p(e){const o=(e-1)*a,{data:t}=await n.get(`${l.PRODUCTS}?limit=${a}&skip=${o}`);return t}async function C(e,o){const t=(e-1)*a,{data:s}=await n.get(`${l.PRODUCTS_BY_CATEGORY}${o}?limit=${a}&skip=${t}`);return s}const c={categoryList:document.querySelector(".categories"),productsList:document.querySelector(".products"),categoryButton:document.querySelector(".categories__btn"),notFound:document.querySelector(".not-found")};function L(e){const t=["all",...e].map(s=>`<li class="categories__item">
   <button class="categories__btn" type="button" data-category="${s}">${s}</button>
 </li>`).join("");c.categoryList.insertAdjacentHTML("beforeend",t),document.querySelector(".categories__btn")&&document.querySelector(".categories__btn").classList.add("categories__btn--active")}function i(e){const o=e.map(({id:t,thumbnail:s,title:g,brand:_,price:m,category:y})=>`<li class="products__item" data-id="${t}">
    <img class="products__image" src="${s}" alt="${g}"/>
    <p class="products__title">${g}</p>
    <p class="products__brand"><span class="products__brand--bold">Brand:${_}</span></p>
    <p class="products__category">Category: ${y}</p>
    <p class="products__price">Price: ${m}$</p>
 </li>
`).join("");c.productsList.insertAdjacentHTML("beforeend",o)}function $(){c.productsList.innerHTML=""}function w(){c.notFound.classList.add("not-found--visible")}function d(e,o="success"){const t={message:e,position:"topRight",timeout:5e3};switch(o){case"success":r.success(t);break;case"error":r.error(t);break;case"warning":r.warning(t);break;case"info":r.info(t);break;default:r.error({message:`Invalid type of toast: ${o}`,position:"topRight",timeout:5e3});break}}let u=1;async function S(){try{const e=await b(),{total:o,products:t}=await p(u);i(t),L(e)}catch(e){console.log(e),d("Something went wrong...","error")}}async function T(e){if(e.target.nodeName!=="BUTTON")return;$();const o=e.target.dataset.category;if(o==="all")try{const{total:t,products:s}=await p(u);i(s)}catch(t){console.log(t),d("Something went wrong...","error")}document.querySelectorAll(".categories__btn").forEach(t=>{t.classList.contains("categories__btn--active")&&t.classList.remove("categories__btn--active")}),e.target.classList.add("categories__btn--active");try{const{total:t,products:s}=await C(u,o);if(s.length!==0)i(s);else{w();return}}catch(t){console.log(t),d("Something went wrong...","error")}}document.addEventListener("DOMContentLoaded",S);c.categoryList.addEventListener("click",T);
//# sourceMappingURL=index.js.map
